import './bootstrap';
import "flyonui/flyonui"
import TomSelect from 'tom-select';
import EditorJS from '@editorjs/editorjs';
import Header from '@editorjs/header';
import Paragraph from '@editorjs/paragraph';
import NestedList from '@editorjs/nested-list';
import Checklist from '@editorjs/checklist';
import Quote from '@editorjs/quote';
import Table from '@editorjs/table';
import Marker from '@editorjs/marker';
import InlineCode from '@editorjs/inline-code';
import Underline from '@editorjs/underline';
import CodeTool from '@editorjs/code';
import RawTool from '@editorjs/raw';
import Delimiter from '@editorjs/delimiter';
import Warning from '@editorjs/warning';
import LinkTool from '@editorjs/link';
import ImageTool from '@editorjs/image';
import SimpleImage from '@editorjs/simple-image';
import Embed from '@editorjs/embed';
import AttachesTool from '@editorjs/attaches';
import Alert from 'editorjs-alert';
import ToggleBlock from 'editorjs-toggle';
import DragDrop from 'editorjs-drag-drop';
import Undo from 'editorjs-undo';
import CodeBox from '@bomdi/codebox';
import Tooltip from 'editorjs-tooltip';
import ChangeCase from 'editorjs-change-case';
import EditorJSColumns from '@calumk/editorjs-columns';
window.TomSelect = TomSelect;
window.EditorJS = EditorJS;
window.EditorJSColumns = EditorJSColumns;
window.Header = Header;
window.Paragraph = Paragraph;
window.NestedList = NestedList;
window.Checklist = Checklist;
window.Quote = Quote;
window.Table = Table;
window.Marker = Marker;
window.InlineCode = InlineCode;
window.Underline = Underline;
window.CodeTool = CodeTool;
window.RawTool = RawTool;
window.Delimiter = Delimiter;
window.Warning = Warning;
window.LinkTool = LinkTool;
window.ImageTool = ImageTool;
window.SimpleImage = SimpleImage;
window.Embed = Embed;
window.AttachesTool = AttachesTool;
window.Alert = Alert;
window.ToggleBlock = ToggleBlock;
window.DragDrop = DragDrop;
window.Undo = Undo;
window.CodeBox = CodeBox;
window.Tooltip = Tooltip;
window.ChangeCase = ChangeCase;
